export const DEMO_USER = {
  id: 'demo-user-1',
  email: 'admin@demo-properties.co.za',
  firstName: 'Admin',
  lastName: 'User',
  role: 'PORTFOLIO_MANAGER',
  organisationId: 'demo-org-1',
};

export const DEMO_STATS = {
  data: {
    totalProperties: 4,
    totalUnits: 48,
    occupiedUnits: 39,
    vacantUnits: 9,
    occupancyRate: 81.25,
    totalLeads: 23,
    activeApplications: 7,
    activeLeases: 36,
  },
};

export const DEMO_PIPELINE = {
  data: {
    NEW: 8,
    CONTACTED: 5,
    QUALIFIED: 4,
    APPLIED: 3,
    SCREENED: 2,
    APPROVED: 1,
    LOST: 3,
  },
};

export const DEMO_PROPERTIES = {
  data: [
    {
      id: 'prop-1',
      name: 'Sandton Central Apartments',
      type: 'APARTMENT_COMPLEX',
      addressLine1: '123 Rivonia Road',
      suburb: 'Sandton',
      city: 'Johannesburg',
      province: 'GAUTENG',
      postalCode: '2196',
      description: 'Luxury apartments in the heart of Sandton CBD',
      _count: { units: 20 },
    },
    {
      id: 'prop-2',
      name: 'Rosebank Garden Village',
      type: 'TOWNHOUSE_COMPLEX',
      addressLine1: '45 Bath Avenue',
      suburb: 'Rosebank',
      city: 'Johannesburg',
      province: 'GAUTENG',
      postalCode: '2196',
      description: 'Charming townhouses with private gardens',
      _count: { units: 12 },
    },
    {
      id: 'prop-3',
      name: 'Sea Point Residences',
      type: 'APARTMENT_COMPLEX',
      addressLine1: '88 Beach Road',
      suburb: 'Sea Point',
      city: 'Cape Town',
      province: 'WESTERN_CAPE',
      postalCode: '8005',
      description: 'Ocean-facing apartments with stunning views',
      _count: { units: 8 },
    },
    {
      id: 'prop-4',
      name: 'Umhlanga Ridge Estate',
      type: 'MIXED_USE',
      addressLine1: '12 Palm Boulevard',
      suburb: 'Umhlanga',
      city: 'Durban',
      province: 'KWAZULU_NATAL',
      postalCode: '4319',
      description: 'Modern mixed-use development near Gateway',
      _count: { units: 8 },
    },
  ],
};

export const DEMO_LEADS = {
  data: [
    {
      id: 'lead-1',
      firstName: 'Thabo',
      lastName: 'Mokoena',
      email: 'thabo@example.co.za',
      phone: '+27 82 123 4567',
      source: 'WEBSITE',
      monthlyIncome: 45000,
      score: 85,
      status: 'QUALIFIED',
      property: { name: 'Sandton Central Apartments' },
    },
    {
      id: 'lead-2',
      firstName: 'Naledi',
      lastName: 'Dlamini',
      email: 'naledi@example.co.za',
      phone: '+27 83 234 5678',
      source: 'AGENT_REFERRAL',
      monthlyIncome: 38000,
      score: 72,
      status: 'CONTACTED',
      property: { name: 'Rosebank Garden Village' },
    },
    {
      id: 'lead-3',
      firstName: 'Pieter',
      lastName: 'van der Merwe',
      email: 'pieter@example.co.za',
      phone: '+27 84 345 6789',
      source: 'WALK_IN',
      monthlyIncome: 55000,
      score: 91,
      status: 'APPLIED',
      property: { name: 'Sea Point Residences' },
    },
    {
      id: 'lead-4',
      firstName: 'Ayanda',
      lastName: 'Nkosi',
      email: 'ayanda@example.co.za',
      phone: '+27 71 456 7890',
      source: 'WEBSITE',
      monthlyIncome: 32000,
      score: 65,
      status: 'NEW',
      property: { name: 'Sandton Central Apartments' },
    },
    {
      id: 'lead-5',
      firstName: 'Sarah',
      lastName: 'Johnson',
      email: 'sarah@example.co.za',
      phone: '+27 82 567 8901',
      source: 'PROPERTY24',
      monthlyIncome: 62000,
      score: 88,
      status: 'SCREENED',
      property: { name: 'Umhlanga Ridge Estate' },
    },
    {
      id: 'lead-6',
      firstName: 'Mohammed',
      lastName: 'Patel',
      email: 'mohammed@example.co.za',
      phone: '+27 83 678 9012',
      source: 'AGENT_REFERRAL',
      monthlyIncome: 41000,
      score: 78,
      status: 'NEW',
      property: { name: 'Rosebank Garden Village' },
    },
  ],
};

export const DEMO_APPLICATIONS = {
  data: [
    {
      id: 'app-1',
      firstName: 'Thabo',
      lastName: 'Mokoena',
      status: 'APPROVED',
      unit: { unitNumber: 'A101', monthlyRent: 12500, property: { name: 'Sandton Central Apartments' } },
      _count: { documents: 4, screeningChecks: 5 },
    },
    {
      id: 'app-2',
      firstName: 'Pieter',
      lastName: 'van der Merwe',
      status: 'SCREENING_IN_PROGRESS',
      unit: { unitNumber: 'SP-3B', monthlyRent: 18000, property: { name: 'Sea Point Residences' } },
      _count: { documents: 3, screeningChecks: 3 },
    },
    {
      id: 'app-3',
      firstName: 'Sarah',
      lastName: 'Johnson',
      status: 'SUBMITTED',
      unit: { unitNumber: 'UR-12', monthlyRent: 15500, property: { name: 'Umhlanga Ridge Estate' } },
      _count: { documents: 2, screeningChecks: 0 },
    },
    {
      id: 'app-4',
      firstName: 'Naledi',
      lastName: 'Dlamini',
      status: 'UNDER_REVIEW',
      unit: { unitNumber: 'RG-7', monthlyRent: 9800, property: { name: 'Rosebank Garden Village' } },
      _count: { documents: 5, screeningChecks: 2 },
    },
    {
      id: 'app-5',
      firstName: 'James',
      lastName: 'Okonkwo',
      status: 'DECLINED',
      unit: { unitNumber: 'A205', monthlyRent: 14000, property: { name: 'Sandton Central Apartments' } },
      _count: { documents: 3, screeningChecks: 5 },
    },
  ],
};

export const DEMO_LEASES = {
  data: [
    {
      id: 'lease-1',
      status: 'ACTIVE',
      monthlyRent: 12500,
      startDate: '2025-03-01',
      endDate: '2026-02-28',
      tenant: { user: { firstName: 'Thabo', lastName: 'Mokoena' } },
      unit: { unitNumber: 'A101', property: { name: 'Sandton Central Apartments' } },
    },
    {
      id: 'lease-2',
      status: 'ACTIVE',
      monthlyRent: 9800,
      startDate: '2025-06-01',
      endDate: '2026-05-31',
      tenant: { user: { firstName: 'Lindiwe', lastName: 'Zulu' } },
      unit: { unitNumber: 'RG-3', property: { name: 'Rosebank Garden Village' } },
    },
    {
      id: 'lease-3',
      status: 'PENDING_SIGNATURE',
      monthlyRent: 18000,
      startDate: '2026-05-01',
      endDate: '2027-04-30',
      tenant: { user: { firstName: 'Pieter', lastName: 'van der Merwe' } },
      unit: { unitNumber: 'SP-3B', property: { name: 'Sea Point Residences' } },
    },
    {
      id: 'lease-4',
      status: 'ACTIVE',
      monthlyRent: 15500,
      startDate: '2025-01-01',
      endDate: '2025-12-31',
      tenant: { user: { firstName: 'Priya', lastName: 'Naidoo' } },
      unit: { unitNumber: 'UR-5', property: { name: 'Umhlanga Ridge Estate' } },
    },
    {
      id: 'lease-5',
      status: 'EXPIRED',
      monthlyRent: 11000,
      startDate: '2024-01-01',
      endDate: '2024-12-31',
      tenant: { user: { firstName: 'David', lastName: 'Botha' } },
      unit: { unitNumber: 'A308', property: { name: 'Sandton Central Apartments' } },
    },
  ],
};

export const DEMO_TENANTS = {
  data: [
    {
      id: 'tenant-1',
      user: { firstName: 'Thabo', lastName: 'Mokoena', email: 'thabo@example.co.za', phone: '+27 82 123 4567' },
      leases: [{ unit: { unitNumber: 'A101', property: { name: 'Sandton Central Apartments' } } }],
    },
    {
      id: 'tenant-2',
      user: { firstName: 'Lindiwe', lastName: 'Zulu', email: 'lindiwe@example.co.za', phone: '+27 83 234 5678' },
      leases: [{ unit: { unitNumber: 'RG-3', property: { name: 'Rosebank Garden Village' } } }],
    },
    {
      id: 'tenant-3',
      user: { firstName: 'Priya', lastName: 'Naidoo', email: 'priya@example.co.za', phone: '+27 84 345 6789' },
      leases: [{ unit: { unitNumber: 'UR-5', property: { name: 'Umhlanga Ridge Estate' } } }],
    },
    {
      id: 'tenant-4',
      user: { firstName: 'David', lastName: 'Botha', email: 'david@example.co.za', phone: '+27 71 456 7890' },
      leases: [],
    },
    {
      id: 'tenant-5',
      user: { firstName: 'Fatima', lastName: 'Essop', email: 'fatima@example.co.za', phone: '+27 82 567 8901' },
      leases: [{ unit: { unitNumber: 'SP-1A', property: { name: 'Sea Point Residences' } } }],
    },
  ],
};
